angle_version = 'le90'
model = dict(
    # type='OrientedRCNN',
    backbone=dict(
        type='ReSoNet',
        stem_dim=96,
        depths=(2, 4, 4, 2),
        num_heads=[8, 8, 8, 8],
        num_points=[8, 8, 8, 8],
        # norm_layer=dict(type='SyncBN', requires_grad=True),
        # norm_layer=dict(type='BN', requires_grad=True), # change to this version for single-GPU training 
        norm_layer='BN', # change to this version for single-GPU training 
        act_layer='ReLU',
        mlp_ratio=2.,
        fork_feat=True,
        drop_path_rate=0.1,
        # init_cfg=None,
        init_cfg=dict(type='Pretrained',
            # checkpoint="/home/zzc/archive/ZZCpretrain/resonet_small/ImageNet-1k/none_pretrain/260417-2143/weights/epoch_50.pth"),
            # checkpoint="/home/zzc/archive/ZZCpretrain/resonet_small/ImageNet-1k/none_pretrain/260417-2143/weights/epoch_60.pth"),
            # checkpoint="/home/zzc/archive/ZZCpretrain/resonet_small/ImageNet-1k/none_pretrain/260417-2143/weights/epoch_70.pth"),
            # checkpoint="/home/zzc/archive/ZZCpretrain/resonet_small/ImageNet-1k/none_pretrain/260417-2143/weights/epoch_55.pth"),
            # checkpoint="/home/zzc/archive/ZZCpretrain/resonet_small/ImageNet-1k/none_pretrain/260417-2143/weights/epoch_65.pth"),
            # checkpoint="/home/zzc/archive/ZZCpretrain/resonet_small/ImageNet-1k/none_pretrain/260417-2143/weights/epoch_80.pth"),
            # checkpoint="/home/zzc/archive/ZZCpretrain/resonet_small/ImageNet-1k/none_pretrain/260422-1248/weights/epoch_280.pth"),
            # checkpoint="/home/zzc/archive/ZZCpretrain/resonet_small/ImageNet-1k/none_pretrain/260422-1248/weights/epoch_244.pth"),
            # checkpoint="/home/zzc/archive/ZZCpretrain/resonet_small/ImageNet-1k/none_pretrain/260422-1248/weights/epoch_298.pth"),
            checkpoint="/home/zzc/archive/ZZCpretrain/resonet_small/ImageNet-1k/none_pretrain/260422-1248/weights/epoch_293.pth"),
        pretrained=None),
    neck=dict(
        type='FPN',
        in_channels=[96, 192, 384, 768],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='OrientedRPNHead',
        in_channels=256,
        feat_channels=256,
        version=angle_version,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='MidpointOffsetCoder',
            angle_range=angle_version,
            target_means=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0, 0.5, 0.5]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(
            type='SmoothL1Loss', beta=0.1111111111111111, loss_weight=1.0)),
    roi_head=dict(
        type='OrientedStandardRoIHead',
        bbox_roi_extractor=dict(
            type='RotatedSingleRoIExtractor',
            roi_layer=dict(
                type='RoIAlignRotated',
                out_size=7,
                sample_num=2,
                clockwise=True),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=dict(
            type='RotatedShared2FCBBoxHead',
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=15,
            bbox_coder=dict(
                type='DeltaXYWHAOBBoxCoder',
                angle_range=angle_version,
                norm_factor=None,
                edge_swap=True,
                proj_xy=True,
                target_means=(.0, .0, .0, .0, .0),
                target_stds=(0.1, 0.1, 0.2, 0.2, 0.1)),
            reg_class_agnostic=True,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))),
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=0,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=2000,
            nms=dict(type='nms', iou_threshold=0.8),
            min_bbox_size=0),
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=False,
                iou_calculator=dict(type='RBboxOverlaps2D'),
                ignore_iof_thr=-1),
            sampler=dict(
                type='RRandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False)),
    test_cfg=dict(
        rpn=dict(
            nms_pre=2000,
            max_per_img=2000,
            nms=dict(type='nms', iou_threshold=0.8),
            min_bbox_size=0),
        rcnn=dict(
            nms_pre=2000,
            min_bbox_size=0,
            score_thr=0.05,
            nms=dict(iou_thr=0.1),
            max_per_img=2000)))
